language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test -- --coverage
  - CI=false npm run build
# deploy:
#   provider: surge
#   skip_cleanup: true
#   domain: <my_name_here>.surge.sh
#   project: ./build/
on:
  branch: test-the-app

after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
