export const LOGIN = "LOGIN";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const SIGNUP = "SIGNUP";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const CLEAR_CREDENTIAL_MESSAGES = "CLEAR_CREDENTIAL_MESSAGES";

export const GET_MENUS = "GET_MENUS";
export const CREATE_MENU = "CREATE_MENU";
export const CREATE_MENU_ERROR = "CREATE_MENU_ERROR";
export const CLEAR_MENU_MESSAGES = "CLEAR_MENU_MESSAGES";

export const GET_MEALS = "GET_MEALS";
export const CREATE_MEAL = "CREATE_MEAL";
export const CREATE_MEAL_ERROR = "CREATE_MEAL_ERROR";
export const CLEAR_MEAL_MESSAGES = "CLEAR_MEAL_MESSAGES";
export const START_EDITING_MEAL = " START_EDITING_MEAL";
export const EDIT_MEAL = "EDIT_MEAL";
export const EDIT_MEAL_ERROR = "EDIT_MEAL_ERROR";
export const FINISH_EDITING_MEAL = "FINISH_EDITING_MEAL";
export const MEAL_DELETED = "MEAL_DELETED";
export const MEAL_DELETION_ERROR = "MEAL_DELETION_ERROR";

export const GET_ORDERS = "GET_ORDERS";
export const CREATE_ORDER = "CREATE_ORDER";
export const CREATE_ORDER_ERROR = "CREATE_ORDER_ERROR";
export const CLEAR_ORDER_MESSAGES = "CLEAR_MENU_MESSAGES";
export const GOT_CUSTOMER_ORDERS = "GOT_CUSTOMER_ORDERS";
